# NumPy

- https://numpy.org/
- O nome NumPy vem de Numerical Python
    - Biblioteca de computação numérica
    - Otimizada para cálculos pesados
<br><br>
- No NumPy vamos trabalhar com **arrays**, que são mais rápidos e mais performáticos que listas
    - Arrays são estruturas de dados que guardam itens **do mesmo tipo** (diferente das listas)
        - **["As operações matemáticas que devem ser executadas em arrays seriam extremamente ineficientes se os arrays não fossem homogêneos."](https://numpy.org/doc/stable/user/absolute_beginners.html#whats-the-difference-between-a-python-list-and-a-numpy-array)** 
    - Assim como **listas**, são um conjunto de **elementos ordenados que são mutáveis e de comprimento variável**
    - Além disso, **podemos fazer várias operações com arrays (como multiplicação e soma) que não podem ser feitas com listas** mas são fundamentais para o nosso processo de Ciência de dados
    - Obs: listas são estrutudas de dados do Python e arrays não, **array é uma estrutura de dados própria do numpy**

In [1]:
# Importar o numpy
import numpy as np

- **A importância do NumPy**
    - Vamos supor que temos a venda e comissão (em percentual) de 5 vendedores e queremos saber qual vai ser o salário de cada um deles (para isso precisamos multiplicar a venda pela comissão dividida por 100)

In [2]:
# Venda e comissão
venda_valor = [150000,230000,82000,143000,184000]
comissao = [5,8,8,5,12]

print(type(venda_valor))
print(type(comissao))

venda_valor=np.array(venda_valor)
comissao=np.array(comissao)

salarios=venda_valor*comissao/100
print(salarios)

<class 'list'>
<class 'list'>
[ 7500. 18400.  6560.  7150. 22080.]


In [3]:
# Qual o tipo desse dado?
print(type(salarios))

<class 'numpy.ndarray'>


In [4]:
# Ao tentar fazer essa operação com listas, teremos um erro
venda_valor2 = [150000,230000,82000,143000,184000]
comissao2 = [5,8,8,5,12]

salarios2=venda_valor2*comissao2/100

TypeError: can't multiply sequence by non-int of type 'list'

- **Podemos transformar uma lista em um array**
    - https://numpy.org/doc/stable/user/basics.creation.html#converting-python-sequences-to-numpy-arrays

In [5]:
# Transformando em um array
# o help imprime uma ajuda sobre o metodo ou atributo
help(np.array)

venda_valor2=np.array(venda_valor2)
comissao2=np.array(comissao2)

print(venda_valor2)
print(comissao2)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [6]:
# Agora vamos conseguir fazer sendo um array
salarios2=venda_valor2*comissao2/100

display(salarios2)

array([ 7500., 18400.,  6560.,  7150., 22080.])

- **Agora que vimos a importância do array, podemos falar um pouco mais sobre ele**
    - https://numpy.org/doc/stable/user/quickstart.html

In [10]:
# Copiando o exemplo
# criamos um array com o 'range' de 0 a 14 e colocamos em 3 linhas e 5 colunas
a = np.arange(15).reshape(3, 5)
print(a)

b = np.arange(2,7)
print(b)

c = np.arange(2,10,2)
print(c)

d = np.array([[1,2,3],[4,5,6]])
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[2 3 4 5 6]
[2 4 6 8]
[[1 2 3]
 [4 5 6]]


In [11]:
# Verificando a dimensão desse array
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

2
1
1
2


In [12]:
# Verificando a forma do array
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(3, 5)
(5,)
(4,)
(2, 3)


In [13]:
# Verificando o tipo dos dados
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)

int32
int32
int32
int32


- Primeiro tente responder o tipo de dado dos 3 arrays abaixo e depois escreva o código para o numpy retornar essa informação

In [14]:
# Considerando os 3 arrays abaixo
array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4.5,5])
array3 = np.array([1,2,3,'4',5])

In [16]:
# Verificando o tipo de dado do primeiro array e retornando esse array
print(array1.dtype)
print(array1)

int32
[1 2 3 4 5]


In [17]:
# Fazendo a mesma coisa para o array2
print(array2.dtype)
print(array2)

float64
[1.  2.  3.  4.5 5. ]


In [18]:
# E para o array3
print(array3.dtype)
print(array3)

<U11
['1' '2' '3' '4' '5']


- **Criando o nosso próprio array**

In [ ]:
# Criando um array qualquer de números inteiros

In [ ]:
# Criando um segundo array com valores decimais

In [ ]:
# Criando um array apenas de valores zero

In [ ]:
# Criando um array com uma lista de valores

In [ ]:
# Adicionando um intervalo para o array

In [ ]:
# Adicionando um "passo" para o array

In [ ]:
# Criando um novo array com os valores igualmente espaçados (utilizando o linspace)

- O array de uma dimensão é o que chamamos de vetor e o de duas dimensões de matriz

In [ ]:
# Vamos considerar esses dados abaixo
dados_venda = np.array([[150000,230000,82000,143000,184000],[5,8,8,5,12]])

In [ ]:
# Verificando a forma do array

In [ ]:
# Verificando o tipo dos dados

In [ ]:
# Agora considerando esses novos dados
dados_venda = np.array([['Lucas','Bia','Jean','Gabi','Pedro'],[150000,230000,82000,143000,184000]])

In [ ]:
# Verificando a forma do array

In [ ]:
# Verificando o tipo dos dados

- **Assim como listas, também podemos buscar elementos no array utilizando seus índices**
    - https://numpy.org/doc/stable/user/basics.indexing.html

In [ ]:
# Utilizando o mesmo array do exemplo
a = np.arange(15).reshape(3, 5)

In [ ]:
# Buscando a primeira linha

In [ ]:
# Na primeira linha, buscando o elemento de índice 3

In [ ]:
# Buscando os elementos de índice 1 a 3 (incluindo o 3) na primeira linha

In [ ]:
# Buscando apenas os valores maiores que 5

In [ ]:
# Buscando valores maiores que 5 E (&) menores que 11

In [ ]:
# Visualizando o array

- **Operações com array**
    - https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations

In [ ]:
# Considerando o array abaixo
dados = np.arange(6).reshape(2, 3)

In [ ]:
# Somando todos os valores

In [ ]:
# Somando apenas os valores da linha

In [ ]:
# Fazendo a soma acumulada desses valores

In [ ]:
# Somando apenas os valores da coluna

In [ ]:
# Somando 1 em todos os valores

In [ ]:
# Multiplicando 2 em todos os valores do array

In [ ]:
# Verificando o menor valor desse array

In [ ]:
# E agora o maior valor

In [ ]:
# Calculando a média da primeira linha

In [ ]:
# E da segunda linha

In [ ]:
# Verificando a mediana

- Inclusive podemos fazer operação entre arrays

In [ ]:
# Considerando esses 2 arrays
array1 = np.array([1,2,3,4,5])
array2 = np.array([7,8,9,10,11])

In [ ]:
# Somando os arrays

In [ ]:
# Multiplicando esses arrays

In [ ]:
# Potência